language: python
python:
  - 2.7.11
addons:
  apt_packages:
    - pandoc
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install -r requirements.txt
before_script:
  - mv fab_settings.py.example fab_settings.py
script:
  - cd mysite
  - pytest
after_success:
  - coveralls
sudo: false
